#!/usr/bin/env bash
# Regenerates assets/screenshot-hero.png and assets/screenshot-italic.png from
# mockups/hero.html and mockups/hero-italic.html via headless Chrome. The two
# HTML files are hand-authored (colors copied from the theme's actual hex
# values), not generated by scripts/build.py -- update them by hand if the
# palette changes.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

"$CHROME" --headless --disable-gpu --screenshot="$ROOT/assets/screenshot-hero.png" \
  --window-size=1000,640 "file://$ROOT/mockups/hero.html"

"$CHROME" --headless --disable-gpu --screenshot="$ROOT/assets/screenshot-italic.png" \
  --window-size=1000,640 "file://$ROOT/mockups/hero-italic.html"

echo "wrote assets/screenshot-hero.png and assets/screenshot-italic.png"
